### PR TITLE
ci: change changelog generation

### PR DESCRIPTION
**Pull request by gaetanars**
Change the generation of changelog and release with a tag on main branch instead of Release Please.

### CODE REVIEW

**Comment by azrod** [comment]
Is it possible to move the entire .ci directory into a dedicated repo to more easily update the template without having to go to each repository?

**Comment by gaetanars** [comment]
I think is not possible, because it contains scripts and template specifics to this repository.

**Comment by azrod** [comment]
The script and the template are not always the same? Can't import it with a GIT submodule?

**Comment by gaetanars** [comment]
This commit remove CI script from repo and add it to a submodule.

**Review by azrod — APPROVED** [review]

**Pull request merged**
